---
apiVersion: v1
kind: Service
metadata:
  name: solana-validator-service
spec:
  ports:
    - name: rpc-port 
      port: 8899
    - name: gossip-port 
      port: 8001
    - name: faucet-port 
      port: 9900
  selector:
    app.kubernetes.io/name: solana-validator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solana-validator-deployment
  labels:
    app.kubernetes.io/name: solana-validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: solana-validator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solana-validator
    spec:
      containers:
        - name: solana-validator
          image: ubuntu:20.04
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BOOTSTRAP_RPC_PORT
              value: "solana-bootstrap-validator-service.$(NAMESPACE).svc.cluster.local:8899"
            - name: BOOTSTRAP_GOSSIP_PORT
              value: "solana-bootstrap-validator-service.$(NAMESPACE).svc.cluster.local:8001"
            - name: BOOTSTRAP_FAUCET_PORT
              value: "solana-bootstrap-validator-service.$(NAMESPACE).svc.cluster.local:9900"
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
